### ISSUE TITLE
Is it possible execute the scrapper to get an updated sample and also more data from the ROS User (e.g. karma, last_seemt_at, etc.) ?

### ISSUE THREAD

**Issue by pestefo** [elbraulio/ros_gh#13]
I need more data from the ROS Answers' user, specifically:

1. **karma**
1. **joined_at**
1. **last_seen_at**
1. **location**
1. has_avatar (or the url to the avatar and NULL if it has the default)
1. description
1. real name (if it exist)

1. age
1. badges (and its count)

I'm particularly interested in the first 4, so if it's it require more effort to get the rest of the list I'd already be happy with havine just those four (karma, joined_at, last_seen_at, location).

**Comment by elbraulio** [comment]
first (short time) I'll include

1.  **karma**
2. **location**
3. description
4. real name
5. age
6. avatar (not sure if Im able to know if is a default avatar)

 Then (days later) badges and the last one will be **joined_at** and **last_seen_at** because the api has the info but I don't know the date format and the [askbot docs are broken](https://github.com/ASKBOT/askbot-devel/issues/779) since September 😑. I've tried to guess the format but I can't get it. This an example of dates:

[https://answers.ros.org/api/v1/users/34668/](https://answers.ros.org/api/v1/users/34668/)

**Comment by elbraulio** [comment]
someone just [uploaded the docs  in the comments 😲](https://github.com/ASKBOT/askbot-devel/issues/779#issuecomment-438273488). Now I'll look in the docs.

**Comment by pestefo** [comment]
joined_at and last_seen_at are in Unix Epoch format
Ex. 1523893495 --> Monday, 16 April 2018 15:44:55 (https://www.epochconverter.com/)

Just save the data as it is, there's no need in converting it to another format: Unix Epoch format is fine.

**Comment by elbraulio** [comment]
I've already added 

1.  **karma**
2. **location**
3. description
4. real name
5. age
6. avatar (*NULL* if default)
7. **joined_at**
8. **last_seen_at**

only badges are missing.

**Comment by elbraulio** [comment]
I'm scraping users and questions. This is a data sample:
**click to see bigger**
<img width="1348" alt="captura de pantalla 2018-12-04 a la s 21 36 16" src="https://user-images.githubusercontent.com/8397094/49482143-aec14d80-f80c-11e8-8287-0966007e4883.png">
I expect to have this tomorrow at morning ✌🏻
